name: Sanpo

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Cache Deno dependencies
        uses: actions/cache@v2
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ runner.os }}-deno-${{ hashFiles('**/lock.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Run tests
        run: deno test
